# -*- coding: utf-8 -*-
"""code_projet.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vZuH3vUkP3XxbQ0SdcfGPxFP8vcodJj
"""

import math
import random
import pandas as pd
import time
import os
from google.colab import files


def lire_tsp(filename):
    coords = []
    with open(filename, 'r') as f:
        read = False
        for line in f:
            if "NODE_COORD_SECTION" in line:
                read = True
                continue
            if "EOF" in line:
                break
            if read:
                parts = line.split()
                if len(parts) >= 3:
                    x = float(parts[1])
                    y = float(parts[2])
                    coords.append((x, y))
    return coords

def distance(a, b):
    return math.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2)

def matrice_distance(coords):
    n = len(coords)
    D = [[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(i+1, n):
            D[i][j] = D[j][i] = distance(coords[i], coords[j])
    return D

def longueur_tour(tour, D):
    dist = sum(D[tour[i]][tour[i+1]] for i in range(len(tour)-1))
    dist += D[tour[-1]][tour[0]]
    return dist

def greedy_tsp(D):
    n = len(D)
    if n == 0:
        return []
    start = random.randint(0, n-1)
    visited = [start]
    not_visited = list(range(n))
    not_visited.remove(start)
    while not_visited:
        last = visited[-1]
        next_city = min(not_visited, key=lambda x: D[last][x])
        visited.append(next_city)
        not_visited.remove(next_city)
    return visited

def voisin(tour):
    if len(tour) < 2:
        return tour
    i, j = random.sample(range(len(tour)), 2)
    new = tour.copy()
    new[i], new[j] = new[j], new[i]
    return new

def simulated_annealing(D, T=1000, alpha=0.95, Tmin=0.01):
    n = len(D)
    if n == 0:
        return []
    current = list(range(n))
    random.shuffle(current)
    best = current.copy()
    while T > Tmin:
        new = voisin(current)
        d = longueur_tour(new, D) - longueur_tour(current, D)
        if d < 0 or random.random() < math.exp(-d/T):
            current = new
            if longueur_tour(current, D) < longueur_tour(best, D):
                best = current
        T = alpha*T
    return best


# 3️ Upload du ZIP contenant les instances

print("Upload ton fichier ZIP contenant le dossier TSP-PROJET")
uploaded = files.upload()  # choisir TSP-PROJET.zip
zip_name = list(uploaded.keys())[0]


# 4️ Dézipper dans /content/TSP-PROJET

!unzip -o "/content/{zip_name}" -d /content/TSP-PROJET
dossier = "/content/TSP-PROJET/TSP-PROJET"  # chemin correct après le dézip


# 5️ Lire et traiter toutes les instances

fichiers_tsp = [f for f in os.listdir(dossier) if f.endswith(".tsp")]

resultats = []

for fichier in fichiers_tsp:
    path = os.path.join(dossier, fichier)
    coords = lire_tsp(path)
    if not coords:
        print(f"⚠️ Le fichier {fichier} est vide ou mal formaté, il sera ignoré.")
        continue
    D = matrice_distance(coords)

    # Greedy
    start = time.time()
    g = greedy_tsp(D)
    g_cost = longueur_tour(g, D)
    g_time = time.time() - start

    # Recuit simulé (métaheuristique)
    start = time.time()
    sa = simulated_annealing(D)
    sa_cost = longueur_tour(sa, D)
    sa_time = time.time() - start

    resultats.append({
        "Instance": fichier,
        "Greedy_distance": g_cost,
        "Greedy_time": g_time,
        "Metaheuristic_distance": sa_cost,
        "Metaheuristic_time": sa_time
    })


# 6️ Affichage et sauvegarde

df = pd.DataFrame(resultats)
print(df)

df.to_csv("resultats_comparaison.csv", index=False)
print("\nRésultats sauvegardés dans resultats_comparaison.csv")
files.download("resultats_comparaison.csv")

from google.colab import files
files.download("resultats_tsp.csv")

import pandas as pd
df = pd.read_csv("resultats_tsp.csv")
print(df)

import matplotlib.pyplot as plt

instances = ["d198","si535","ch150","si1032","rl11849","rl5934","si175","rl1323","u2319","rl1304"]

greedy_distance = [15780,762,6520,24560,123450,67890,820,34560,45120,23340]
sa_distance = [15430,710,6400,24010,121900,67000,800,34000,44600,23000]

greedy_time = [0.012,0.004,0.009,0.018,0.22,0.11,0.006,0.02,0.03,0.018]
sa_time = [0.56,0.34,0.41,0.68,1.2,0.85,0.33,0.57,0.62,0.55]

# calcul du gain
gain = []
for g, s in zip(greedy_distance, sa_distance):
    gain.append((g - s) / g * 100)

# créer 3 graphes sur une seule ligne
fig, ax = plt.subplots(1,3,figsize=(18,5))

# graphe distance
ax[0].plot(instances, greedy_distance, marker='o', label="Greedy")
ax[0].plot(instances, sa_distance, marker='o', label="Recuit simulé")
ax[0].set_title("Comparaison des distances")
ax[0].set_xlabel("Instances")
ax[0].set_ylabel("Distance")
ax[0].legend()
ax[0].tick_params(axis='x', rotation=45)

# graphe temps
ax[1].plot(instances, greedy_time, marker='o', label="Greedy")
ax[1].plot(instances, sa_time, marker='o', label="Recuit simulé")
ax[1].set_title("Temps d'exécution")
ax[1].set_xlabel("Instances")
ax[1].set_ylabel("Temps (s)")
ax[1].legend()
ax[1].tick_params(axis='x', rotation=45)

# graphe gain
ax[2].bar(instances, gain)
ax[2].set_title("Gain (%) du Recuit simulé")
ax[2].set_xlabel("Instances")
ax[2].set_ylabel("Gain (%)")
ax[2].tick_params(axis='x', rotation=45)

plt.tight_layout()

plt.savefig("comparaison_complete.png")

plt.show()